version: '3.5'

services:
  lineapy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dvc:/dvc
      - ./notebook:/notebook
    command: lineapy jupyter nbconvert --to notebook --execute /notebook/example.ipynb
  dvc:
    build: 
      context: ./dvc
      dockerfile: data_housing_pipeline_Dockerfile
    volumes:
      - ./data:/home/data
